#pragma once

#define WINDOW_CLASS_NAME L"Castlevania"
#define MAIN_WINDOW_TITLE L"Castlevania"

#define BACKGROUND_COLOR 0
#define SCREEN_WIDTH	17 * 16 //+ 800
#define SCREEN_HEIGHT	HUD_HEIGHT + 16 * 14// + 300

#define MAX_FRAME_RATE	120

#define HUD_HEIGHT			40

#define ID_SIMON			0
#define ID_WHIP				1

#define ID_WALL				10
#define ID_PORTAL			11
#define ID_TORCH			12
#define ID_CANDLE			13
#define ID_STAIR			14
#define ID_MAPSET			15
#define ID_ENEMY_SPAWNER	16
#define ID_WATER			17
#define ID_DOOR				18

#define ID_PANTHER			30
#define ID_GHOUL			31
#define ID_BAT				32
#define ID_FISHMAN			33
#define ID_BULLET			34

#define ID_ITEM_SMALL_HEART				20
#define ID_ITEM_LARGE_HEART				21
#define ID_ITEM_WHIP_UPGRADE			22
#define ID_ITEM_DAGGER					23
#define ID_ITEM_AXE						24
#define ID_ITEM_HOLY_WATER				25
#define ID_ITEM_STOPWATCH				26
#define ID_ITEM_BOOMERANG				27
#define ID_ITEM_INVINCIBILITY_POTION	28
#define ID_ITEM_CROSS					29
#define ID_MONEY_BAG_RED				60
#define ID_MONEY_BAG_PURPLE				61
#define ID_MONEY_BAG_WHITE				62
#define ID_MONEY_BAG_BONUS				63

#define ID_SUBWEAPON_DAGGER				40
#define ID_SUBWEAPON_AXE				41
#define ID_SUBWEAPON_HOLY_WATER			42
#define ID_SUBWEAPON_STOPWATCH			43
#define ID_SUBWEAPON_BOOMERANG			44

#define ID_BOSS_PHANTOM_BAT				51

#define STATE_DESTROYED			99

#define ID_TEX_BBOX				-100		// special texture to draw object bounding box
#define ID_TEX_TILESET_01		-10
#define ID_TEX_SIMON			0
#define ID_TEX_ENEMY			10
#define ID_TEX_MISC				20
#define ID_TEX_OBJECT			30
#define ID_TEX_ITEM				40
#define ID_TEX_HUD_BG			50
#define ID_TEX_HEALTH			51
#define ID_TEX_BOSS				60

#define ID_ANI_SIMON_IDLE_RIGHT					100
#define ID_ANI_SIMON_IDLE_LEFT					101
#define ID_ANI_SIMON_WALK_RIGHT					102
#define ID_ANI_SIMON_WALK_LEFT					103
#define ID_ANI_SIMON_ATTACK_RIGHT				104
#define ID_ANI_SIMON_ATTACK_LEFT				105
#define ID_ANI_SIMON_SIT_RIGHT					106
#define ID_ANI_SIMON_SIT_LEFT					107
#define ID_ANI_SIMON_SIT_ATTACK_RIGHT			108
#define ID_ANI_SIMON_SIT_ATTACK_LEFT			109
#define ID_ANI_SIMON_DIE						110
#define ID_ANI_SIMON_IDLE_UP_STAIR_RIGHT		121
#define ID_ANI_SIMON_IDLE_UP_STAIR_LEFT			122
#define ID_ANI_SIMON_IDLE_DOWN_STAIR_RIGHT		123
#define ID_ANI_SIMON_IDLE_DOWN_STAIR_LEFT		124
#define ID_ANI_SIMON_WALK_UP_STAIR_RIGHT		125
#define ID_ANI_SIMON_WALK_UP_STAIR_LEFT			126
#define ID_ANI_SIMON_WALK_DOWN_STAIR_RIGHT		127
#define ID_ANI_SIMON_WALK_DOWN_STAIR_LEFT		128
#define ID_ANI_SIMON_ATTACK_UP_STAIR_RIGHT		129
#define ID_ANI_SIMON_ATTACK_UP_STAIR_LEFT		130
#define ID_ANI_SIMON_ATTACK_DOWN_STAIR_RIGHT	131
#define ID_ANI_SIMON_ATTACK_DOWN_STAIR_LEFT		132
#define ID_ANI_SIMON_DAMAGED_DEFLECT_RIGHT		133
#define ID_ANI_SIMON_DAMAGED_DEFLECT_LEFT		134
#define ID_ANI_SIMON_FLASH_RIGHT				135
#define ID_ANI_SIMON_FLASH_LEFT					136

#define ID_ANI_WHIP_0_RIGHT				111
#define ID_ANI_WHIP_0_LEFT				112
#define ID_ANI_WHIP_1_RIGHT				113
#define ID_ANI_WHIP_1_LEFT				114
#define ID_ANI_WHIP_2_RIGHT				115
#define ID_ANI_WHIP_2_LEFT				116

#define ID_ANI_LARGE_HEART				300
#define ID_ANI_SMALL_HEART				302
#define ID_ANI_CROSS_ITEM				304
#define ID_ANI_STOPWATCH_ITEM			305
#define ID_ANI_BOOMERANG_ITEM			306
#define ID_ANI_INVINCIBILITY_POTION		307
#define ID_ANI_MONEY_BAG_RED			308
#define ID_ANI_MONEY_BAG_PURPLE			309
#define ID_ANI_MONEY_BAG_WHITE			310
#define ID_ANI_MONEY_BAG_BONUS			311
#define ID_ANI_MONEY_BAG_RED_SCORE		312
#define ID_ANI_MONEY_BAG_PURPLE_SCORE	313
#define ID_ANI_MONEY_BAG_WHITE_SCORE	314
#define ID_ANI_MONEY_BAG_BONUS_SCORE	315
#define ID_ANI_DAGGER_ITEM				320
#define ID_ANI_AXE_ITEM					332
#define ID_ANI_HOLY_WATER_ITEM			344

#define ID_ANI_DAGGER_RIGHT				320
#define ID_ANI_DAGGER_LEFT				321
#define ID_ANI_AXE_RIGHT				330
#define ID_ANI_AXE_LEFT					331
#define ID_ANI_HOLY_WATER_RIGHT			340
#define ID_ANI_HOLY_WATER_LEFT			341
#define ID_ANI_HOLY_WATER_FIRED			342
#define ID_ANI_BOOMERANG_RIGHT			345
#define ID_ANI_BOOMERANG_LEFT			346

#define ID_ANI_ENEMY_ON_FIRE			400

#define ID_ANI_PANTHER_IDLE_RIGHT		411
#define ID_ANI_PANTHER_IDLE_LEFT		412
#define ID_ANI_PANTHER_RUN_RIGHT		413
#define ID_ANI_PANTHER_RUN_LEFT			414
#define ID_ANI_PANTHER_JUMP_RIGHT		415
#define ID_ANI_PANTHER_JUMP_LEFT		416

#define ID_ANI_GHOUL_WALK_RIGHT			421
#define ID_ANI_GHOUL_WALK_LEFT			422

#define ID_ANI_BAT_IDLE_RIGHT			431
#define ID_ANI_BAT_IDLE_LEFT			432
#define ID_ANI_BAT_FLY_RIGHT			433
#define ID_ANI_BAT_FLY_LEFT				434

#define ID_ANI_FISHMAN_IDLE_RIGHT		441
#define ID_ANI_FISHMAN_IDLE_LEFT		442
#define ID_ANI_FISHMAN_WALK_RIGHT		443
#define ID_ANI_FISHMAN_WALK_LEFT		444
#define ID_ANI_FISHMAN_ATTACK_RIGHT		445
#define ID_ANI_FISHMAN_ATTACK_LEFT		446

#define ID_ANI_BULLET_RIGHT				451
#define ID_ANI_BULLET_LEFT				452

#define ID_ANI_WATER_EFFECT				500

#define ID_ANI_DOOR_OPEN				231
#define ID_ANI_DOOR_CLOSE				232
#define ID_ANI_DOOR_OPENING				233
#define ID_ANI_DOOR_CLOSING				234

#define ID_ANI_PHANTOM_BAT_IDLE			511
#define ID_ANI_PHANTOM_BAT_ACTIVE		512
#define ID_ANI_PHANTOM_BAT_ON_FIRE		513

